name: Aspire pharmacy
favicon: null
layout_spectrum: 0.01043
typography_spectrum: 0.74936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0383da'
    - '#6db90e'
    - '#378807'
    - '#84c1ec'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
